<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Route extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function (self $route) {
            try {
                RouteSeat::factory($route->bus->seats_capacity)->create([
                    "route_id" => $route->id
                ]);
            } catch (\Exception $e){
                logger('Route observer can not generate route seats');
            }
        });

    }


    public function stations(){
        return $this->hasMany(RouteStation::class, 'route_id', 'id');
    }

    public function seats()
    {
        return $this->hasMany(RouteSeat::class,'route_id','id');
    }

    public function bus()
    {
        return $this->belongsTo(Bus::class, 'bus_id','id');
    }
}
